### ISSUE TITLE
System B produces more than 1 row per measurement

### ISSUE THREAD

**Issue by darioalessandro** [darioalessandro/17655-D#18]
Hey Amine:

I noticed that System B produces more than 1 row per measurement. 

Also, there are rows with no data.

Using flight data as the input you should generate exactly 100 rows of data:

```
xxd -c 72 FlightData.dat > FlightData.txt
```

```
wc -l FlightData.txt
     100 FlightData.txt
```

Please consider following ```SystemA``` approach which parses the measurements into Measurement object prior to performing any computations.

CC @hangyao

**Comment by amine-bellamkaddem** [comment]
you are right Dario, Thanks
Fixed

**Comment by darioalessandro** [comment]
cool :)
