### ISSUE TITLE
Presentation date

### ISSUE THREAD

**Issue by PaulFenton** [darioalessandro/17655-D#2]
From her comments on 02/14/2018:

A1 assignment presentations will be on 26 Feb Monday if everyone is fine with that.  Otherwise you'll be presenting A1 presentation on 21 Feb

26 worked for Hang and I, but you guys should contact her if we need to do them on 21

**Comment by hangyao** [comment]
Works for me

**Comment by darioalessandro** [comment]
26 works for me as well :)

**Comment by darioalessandro** [comment]
I setup cmu17655-d.slack.com to chat.

**Comment by kayvanhaverbeck** [comment]
Fine by me!

**Comment by darioalessandro** [comment]
@PaulFenton @hangyao @kayvanhaverbeck @amine-bellamkaddem 

Should we send https://docs.google.com/presentation/d/1MlJfiSgKy43a-dGZA6OQcOmSq7JI6YpCO7Udv_bDwUY/edit?usp=sharing?

**Comment by darioalessandro** [comment]
I'll send it to Deb to meet the deadline, I suppose that it is ok if we revise it and send it again.
