### ISSUE TITLE
I completed system A diagram

### ISSUE THREAD

**Issue by darioalessandro** [darioalessandro/17655-D#21]
Diagram is available at https://docs.google.com/document/d/1BLR8-3vGbXPojxHMpmY3eHgIqyUJcleR33XIRbMKsqA/edit?usp=sharing

**Comment by darioalessandro** [comment]
CC @amine-bellamkaddem @hangyao @PaulFenton  @kayvanhaverbeck  ^^

**Comment by darioalessandro** [comment]
I'll do another version using ACMELab

**Comment by darioalessandro** [comment]
@hangyao @kayvanhaverbeck  can you guys help me to port the diagram to ACMElab?

**Comment by kayvanhaverbeck** [comment]
I can do this in acme lab! @darioalessandro

**Comment by amine-bellamkaddem** [comment]
@kayvanhaverbeck Does your eclipse allow you to add legend to the diagram ?

**Comment by kayvanhaverbeck** [comment]
No it does not. I was able to reproduce the same shapes and colors in drawio. The file is in the shared google drive

**Comment by kayvanhaverbeck** [comment]
I just added System C diagram to Google Drive folder.

**Comment by PaulFenton** [comment]
Thanks Kayla,


Also made a few final changes, mainly to system C. We added the "BufferedSmoothingFilter" ahead of the second split. This filter is also used in system B.


I think we also have time to factor out the "WildPointsLogFilter" sub-system into a generic component.

These changes are reflected in the rough diagrams on google drive.


After these changes I don't think we have any further plans to modify the code, unless anyone else has anything I'm missing.


-Paul

________________________________

**Comment by kayvanhaverbeck** [comment]
Okay. Thanks for letting me know. Let me know when the changes are done and i'll modify it one last time for everyone. 

What is the team name for the assignment?

**Comment by darioalessandro** [comment]
A1

2018-02-24 21:36 GMT-05:00 kayvanhaverbeck <notifications@github.com>:
