### ISSUE TITLE
Develop generic "split on condition" filter

### ISSUE THREAD

**Issue by PaulFenton** [darioalessandro/17655-D#27]

**Comment by darioalessandro** [comment]
Hey Paul, for system B I developed a dumb split filter, I think that it should be possible to build on it:

https://github.com/darioalessandro/17655-D/blob/master/A1-2015/Library/SplitFilter.java

I call it dumb because it merely broadcasts it's input to all the connected outputs.

**Comment by PaulFenton** [comment]
looks good
