### ISSUE TITLE
Meeting time?

### ISSUE THREAD

**Issue by hangyao** [darioalessandro/17655-D#4]
Let's set up a meeting time over this weekend and next week.

I'll be available on Sat 17th, Sun 18th morning and evening, and after 6 pm CST during weekdays.

**Comment by darioalessandro** [comment]
kk I'll reply in an email so that everyone sees this.

**Comment by darioalessandro** [comment]
I setup cmu17655-d.slack.com to have the meeting and sent an email with our availability tomorrow.
