### ISSUE TITLE
Yarn Install

### ISSUE THREAD

**Issue by kayvanhaverbeck** [darioalessandro/17655-D#49]
I've been trying to do the yarn install commands for the front end for the last two days and it keeps error-ing out saying:   Error: https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30000813.tgz: ESOCKETTIMEDOUT

I'm not sure where this is coming from, but it stoping me from being able to run the front end!

Can someone help me? 

![image](https://user-images.githubusercontent.com/36541175/37576869-ecb663da-2b04-11e8-95b7-3311484e1355.png)

**Comment by darioalessandro** [comment]
Hi Kayla it sounds like a firewall issue to me. Are you using a GM laptop? If so I suggest trying with a non GM computer. Turning off the vpn might help.

**Comment by darioalessandro** [comment]
If you really want to use the GM laptop I think that you can setup a proxy but I do not know the url, Paul can you help?

**Comment by darioalessandro** [comment]
@PaulFenton have you encountered this ^^?

**Comment by PaulFenton** [comment]
I've been usign npm... but I definitely have problems getting thru GM proxy since they added authentication.

I think best bet is to go home, turn off your vpn, and make sure you don't have any environment variables or config files interfering with your proxy settings (you shouldn't need proxy at home)

**Comment by kayvanhaverbeck** [comment]
i turned off my vpn and removed all proxies!

**Comment by darioalessandro** [comment]
@kayvanhaverbeck are you still experiencing the same issues?

I tried to download https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30000813.tgz directly and it works for me, I still think something is blocking your internet connection.
