### ISSUE TITLE
Parallelize filters in SystemA

### ISSUE THREAD

**Issue by darioalessandro** [darioalessandro/17655-D#9]

**Comment by amine-bellamkaddem** [comment]
I found difficulties to reason about parallel filters, how to synchronize data inputs (in the sink), how to assure integrity (in case filter 1 sends data more quickly than filter 2). I began System B using a linear style (and using Dario classes for temperature and altitude). I think, we 2 options:
  - performance => parallel filters, but this will increase complexity, might cause integrity issues, etc
  - integrity, reliability => linear path (in fact this is the default schema of pipe-filters, that is each filter updates data, and sends the result/output to the downstream filter)

What do you think ?

**Comment by hangyao** [comment]
I think we can close this issue since after adding data parsing part, it seems no need to parallelize midfilters.

**Comment by amine-bellamkaddem** [comment]
Yep
